function writeAbaqusInp_Hex_whole_rigbox_skull_2steps(filename, brainNodes, brainElements, materialOrientations, nodeSets, elementSets,regionNums)
    % This function writes the nodes, elements, and materials to an ABAQUS .inp file.
    % Inputs:
    %   filename - name of the .inp file
    %   brainNodes - Nx3 array of node coordinates for whole brain
    %   brainElements - Mx8 array of element connectivity for whole brain
    %   materialOrientations - Mx3x3 array of material orientations for gray matter elements

    fid = fopen(filename, 'w');
    [~, caseName, ~] = fileparts(filename);
   
    fprintf(fid, '** Job name: %s Model name: %s \n',caseName,caseName); 
    fprintf(fid, '** Generated by MATLAB Script\n');

    fprintf(fid, '** PARTS\n');
    fprintf(fid, '**\n');
    
    % Write brain part
    fprintf(fid, '*Part, name=Brain\n');
    
    % Write node data for Brain
    fprintf(fid, '*Node\n');
    for i = 1:size(brainNodes, 1)
        fprintf(fid, '%d, %.6f, %.6f, %.6f\n', i, brainNodes(i, 1), brainNodes(i, 2), brainNodes(i, 3));
    end
    
    % Write element data for brain
    fprintf(fid, '*Element, type=C3D8R\n');
    for i = 1:size(brainElements, 1)
        fprintf(fid, '%d, %6d, %6d, %6d, %6d, %6d, %6d, %6d, %6d\n', i, brainElements(i, :));
    end
       

    % Create node and element set for all gray matter points and elements
    fprintf(fid, '*Nset, nset=Set-node-gray\n');
    for j = 1:length(nodeSets{regionNums+1})
        fprintf(fid, '%7d', nodeSets{regionNums+1}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(nodeSets{regionNums+1})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    fprintf(fid, '*Elset, elset=Set-elem-gray\n');
    for j = 1:length(elementSets{regionNums+1})
        fprintf(fid, '%7d', elementSets{regionNums+1}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+1})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create node sets for gray matter regions
    for region = 0:regionNums-1
        fprintf(fid, '*Nset, nset=Set-node-gray-region%02d\n', region);
        for j = 1:length(nodeSets{region+1})
            fprintf(fid, '%7d', nodeSets{region+1}(j)); % 6 spaces for alignment
            if mod(j, 16) == 0 || j == length(nodeSets{region+1})
                fprintf(fid, '\n');
            else
                fprintf(fid, ', ');
            end
        end
    end
    
    % Create element sets for gray matter regions
    for region = 0:regionNums-1
        fprintf(fid, '*Elset, elset=Set-elem-gray-region%02d\n', region);
        for j = 1:length(elementSets{region+1})
            fprintf(fid, '%7d', elementSets{region+1}(j)); % 6 spaces for alignment
            if mod(j, 16) == 0 || j == length(elementSets{region+1})
                fprintf(fid, '\n');
            else
                fprintf(fid, ', ');
            end
        end
    end
    
    % Create node set for outermost elements close to gray surface
    fprintf(fid, '*Nset, nset=Set-node-gray-outermost\n');
    for j = 1:length(nodeSets{regionNums+4})
        fprintf(fid, '%7d', nodeSets{regionNums+4}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(nodeSets{regionNums+4})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create element set for outermost elements close to gray surface
    fprintf(fid, '*Elset, elset=Set-elem-gray-outermost\n');
    for j = 1:length(elementSets{regionNums+4})
        fprintf(fid, '%7d', elementSets{regionNums+4}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+4})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create node and element set for all white matter points and elements
    fprintf(fid, '*Nset, nset=Set-node-white\n');
    for j = 1:length(nodeSets{regionNums+2})
        fprintf(fid, '%7d', nodeSets{regionNums+2}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(nodeSets{regionNums+2})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    fprintf(fid, '*Elset, elset=Set-elem-white\n');
    for j = 1:length(elementSets{regionNums+2})
        fprintf(fid, '%7d', elementSets{regionNums+2}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+2})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create node set for white surface
    fprintf(fid, '*Nset, nset=Set-node-white-outermost\n');
    for j = 1:length(nodeSets{regionNums+5})
        fprintf(fid, '%7d', nodeSets{regionNums+5}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(nodeSets{regionNums+5})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create element set for white surface
    fprintf(fid, '*Elset, elset=Set-elem-white-outermost\n');
    for j = 1:length(elementSets{regionNums+5})
        fprintf(fid, '%7d', elementSets{regionNums+5}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+5})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create node set for boundary surface
    fprintf(fid, '*Nset, nset=Set-node-boundary\n');
    for j = 1:length(nodeSets{regionNums+3})
        fprintf(fid, '%7d', nodeSets{regionNums+3}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(nodeSets{regionNums+3})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end

    % Create element set for boundary surface
    fprintf(fid, '*Elset, elset=Set-elem-boundary\n');
    for j = 1:length(elementSets{regionNums+3})
        fprintf(fid, '%7d', elementSets{regionNums+3}(j)); % 6 spaces for alignment
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+3})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end 
    
    % Create surface set for outermost elements 
    fprintf(fid, '*Elset, elset=_Surf-gray_S2, internal\n');
    for j = 1:length(elementSets{regionNums+4})
        fprintf(fid, '%7d', elementSets{regionNums+4}(j)); 
        if mod(j, 16) == 0 || j == length(elementSets{regionNums+4})
            fprintf(fid, '\n');
        else
            fprintf(fid, ', ');
        end
    end
    fprintf(fid, '*Surface, type=ELEMENT, name= Surf-gray\n');
    fprintf(fid, '_Surf-gray_S2, S2\n');

    % Create sections for white matter regions
    fprintf(fid, '** Section: Section-white\n');
    fprintf(fid, '*Solid Section, elset=Set-elem-white, material=white\n');

    % Create sections with material orientations for gray matter regions
    fprintf(fid, '*Orientation, name=Ori-GrayOrientation, system=RECTANGULAR\n');
    fprintf(fid, 'GrayOrientation\n');
    fprintf(fid, '1, 0.\n');
    for region = 0:regionNums-1
        fprintf(fid, '** Section: Section-gray%02d\n', region);
        fprintf(fid, '*Solid Section, elset=Set-elem-gray-region%02d, orientation=Ori-GrayOrientation, material=gray_region_%02d\n', region, region);
    end

    % Write material orientation distribution table for gray matter
    fprintf(fid, '*Distribution, name=GrayOrientation, location=ELEMENT, table=GrayOrientationTable\n');
    fprintf(fid, ', %12.1f, %12.1f, %12.1f, %12.1f, %12.1f, %12.1f\n',1,0,0,0,1,0);
    for i = 1:size(elementSets{regionNums+1}, 1)
        orientation = reshape(materialOrientations(i, :, :), 3, 3);
        fprintf(fid, '%d, %12.6f, %12.6f, %12.6f, %12.6f, %12.6f, %12.6f\n', i, orientation(:,1), orientation(:,2));
    end
    fprintf(fid, '*End Part\n');
    fprintf(fid, '**\n');

    fprintf(fid, '*Part, name=Falx\n');
    fprintf(fid, '*Node\n');
    len_node_Falx = size(nodeSets{regionNums + 6}, 1);
    len_elem_Falx = size(elementSets{regionNums + 6}, 1);
    for i = 1:len_node_Falx
        fprintf(fid, '%d, %.6f, %.6f, %.6f\n', nodeSets{regionNums + 6}(i, :));
    end

    fprintf(fid, '*Element, type=R3D4\n');
    for i = 1:len_elem_Falx
        fprintf(fid, '%d, %d, %d, %d, %d \n', elementSets{regionNums + 6}(i, :));
    end
    fprintf(fid, '*Elset, elset=Falx_WALL, generate\n');
    fprintf(fid, '1, %d,  1\n',max(elementSets{regionNums + 6}(:, 1)));
    fprintf(fid, '*End Part\n');

    fprintf(fid, '**\n');
    fprintf(fid, '*Part, name=Skull\n');

    fprintf(fid, '*Node\n');
    len_node_Skull = size(nodeSets{regionNums + 7}, 1);
    len_elem_Skull = size(elementSets{regionNums + 7}, 1);
    for i = 1:len_node_Skull
        fprintf(fid, '%d, %.6f, %.6f, %.6f\n', nodeSets{regionNums + 7}(i, :));
    end

    fprintf(fid, '*Element, type=R3D3\n');
    for i = 1:len_elem_Skull
        fprintf(fid, '%d, %d, %d, %d \n', elementSets{regionNums + 7}(i, :));
    end
    fprintf(fid, '*Elset, elset=SKULL_INNER, generate\n');
    fprintf(fid, '1, %d,  1\n',max(elementSets{regionNums + 7}(:, 1)));
    fprintf(fid, '*End Part\n');

    % Generate Assembly
    fprintf(fid, '**\n');
    fprintf(fid, '** Assembly\n');
    fprintf(fid, '**------------------------------------------------\n');
    fprintf(fid, '*Assembly, name=Assembly\n');
    fprintf(fid, '**\n');
    fprintf(fid, '*Instance, name=BRAIN-1, part=BRAIN\n');
    fprintf(fid, '*End Instance\n');
    fprintf(fid, '**\n');
    fprintf(fid, '*Instance, name=Falx-1, part=Falx\n');
    fprintf(fid, '*End Instance\n');
    fprintf(fid, '**\n');
    fprintf(fid, '*Instance, name=Skull-1, part=Skull\n');
    fprintf(fid, '*End Instance\n');
    fprintf(fid, '**\n');  

    fprintf(fid, '*Node\n');
    fprintf(fid, '%d, %.6f, %.6f, %.6f\n', len_node_Falx+1, nodeSets{regionNums + 8}(1,:));
    fprintf(fid, '*Nset, nset=Set-RP-Falx\n');
    fprintf(fid, '%d\n', len_node_Falx+1);
    fprintf(fid, '*Rigid Body, elset=Falx-1.Falx_WALL, ref node=Set-RP-Falx\n');

    fprintf(fid, '*Node\n');
    fprintf(fid, '%d, %.6f, %.6f, %.6f\n', len_node_Skull+1, nodeSets{regionNums + 8}(2,:));
    fprintf(fid, '*Nset, nset=Set-RP-Skull\n');
    fprintf(fid, '%d\n', len_node_Skull+1);
    fprintf(fid, '*Rigid Body, elset=Skull-1.SKULL_INNER, ref node=Set-RP-Skull\n');

    fprintf(fid, '*End Assembly\n');
    fprintf(fid, '**\n');
    fprintf(fid, '*Amplitude, name=Amp-tabular1\n');
    fprintf(fid, '%.6f, %.6f\n', 0.0, 0.0);
    fprintf(fid, '%.6f, %.6f\n', 0.08, 0.08);   
    fprintf(fid, '**\n');
    
    fprintf(fid, '*Amplitude, name=Amp-tabular2\n');
    fprintf(fid, '%.6f, %.6f\n', 0.0, 0.08);
    fprintf(fid, '%.6f, %.6f\n', 0.17, 0.25);
    fprintf(fid, '**\n');

    fprintf(fid, '*Amplitude, name=Amp-tabular3\n');
    fprintf(fid, '%.6f, %.6f\n', 0.0, 0.08);
    fprintf(fid, '%.6f, %.6f\n', 0.17, 0.34);
    fprintf(fid, '**\n');

    % Write material distribution table part end
    fprintf(fid, '*Distribution Table, name=GrayOrientationTable\n');
    fprintf(fid, 'COORD3D, COORD3D\n');
    
    % Write material definitions outside the part sections
    fprintf(fid, '**\n');
    fprintf(fid, '** MATERIALS\n');
    fprintf(fid, '**\n');

    base_density_value = 1.05e-9;
    increasement_density_value = 1.0e-14;

    for region = 0:regionNums-1
        value = base_density_value + region * increasement_density_value;  % Update the value for each regionIdx
        fprintf(fid, '*Material, name=gray_region_%02d\n', region);
        fprintf(fid, '*Density\n');
        fprintf(fid, '%.5e\n', value);
        fprintf(fid, '*Expansion, type=ORTHO, user\n');
        fprintf(fid, '*Hyperelastic, neo hooke\n');
        fprintf(fid, '5.2e-05, 1\n');
    end
 
    % Write white matter material definition
    fprintf(fid, '*Material, name=white\n');
    fprintf(fid, '*Density\n');
    fprintf(fid, '1.02e-09\n');
    fprintf(fid, '*Expansion, user\n');
    fprintf(fid, '*Hyperelastic, neo hooke\n');
    fprintf(fid, '7.5e-05, 1\n');
    fprintf(fid, '*Viscoelastic, time=PRONY\n');
    fprintf(fid, '0.5,   0., 0.5\n');

    % Write the INTERACTION PROPERTIES, BOUNDARY CONDITIONS, PREDEFINED FIELDS, INTERACTIONS, and STEP sections
    fprintf(fid, '** \n');
    fprintf(fid, '** INTERACTION PROPERTIES\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Surface Interaction, name=IntProp-1\n');
    fprintf(fid, '*Friction\n');
    fprintf(fid, '0.,\n');
    fprintf(fid, '*Surface Behavior, pressure-overclosure=HARD\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** BOUNDARY CONDITIONS\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Name: BC-1 Type: Symmetry/Antisymmetry/Encastre\n');
    fprintf(fid, '*Boundary\n');
    fprintf(fid, 'BRAIN-1.SET-NODE-BOUNDARY, XSYMM\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Name: BC-2 Type: Symmetry/Antisymmetry/Encastre\n');
    fprintf(fid, '*Boundary\n');
    fprintf(fid, 'SET-RP-Falx, ENCASTRE\n');
    fprintf(fid, '** \n');    
    fprintf(fid, '** Name: BC-3 Type: Symmetry/Antisymmetry/Encastre\n');
    fprintf(fid, '*Boundary\n');
    fprintf(fid, 'SET-RP-Skull, ENCASTRE\n');
    fprintf(fid, '** \n'); 
    fprintf(fid, '** PREDEFINED FIELDS\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Name: Predefined Field-1   Type: Temperature\n');
    fprintf(fid, '*Initial Conditions, type=TEMPERATURE\n');
    fprintf(fid, 'BRAIN-1.SET-NODE-GRAY, 0.\n');
    fprintf(fid, '** Name: Predefined Field-2   Type: Temperature\n');
    fprintf(fid, '*Initial Conditions, type=TEMPERATURE\n');
    fprintf(fid, 'BRAIN-1.SET-NODE-WHITE, 0.\n');
    fprintf(fid, '** \n');
    
    fprintf(fid, '** ----------------------------------------------------------------\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** STEP: Step-1\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Step, name=Step-1, nlgeom=YES\n');
    fprintf(fid, '*Dynamic, Explicit\n');
    fprintf(fid, ', 0.08\n');
    fprintf(fid, '*Bulk Viscosity\n');
    fprintf(fid, '0.06, 1.2\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Mass scaling\n');
    fprintf(fid, '*Fixed Mass Scaling, dt=0.000005, type=below min\n');
    fprintf(fid, '** \n');    
    fprintf(fid, '** LOAD\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Name: Load-1   Type: Pressure\n');
    fprintf(fid, '*Dsload\n');
    fprintf(fid, 'BRAIN-1.SURF-GRAY, P, 5.12e-05\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** PREDEFINED FIELDS\n');
    fprintf(fid, '** \n');  

    fprintf(fid, '** Name: Predefined Field-3   Type: Temperature Using Field: DiscField-1\n');
    fprintf(fid, '*Temperature, amplitude = Amp-tabular1\n');
    for nodeidx = 1:size(brainNodes,1)
        fprintf(fid, 'BRAIN-1.%d, %.3f\n',nodeidx, nodeSets{regionNums+9}(nodeidx));
    end

    fprintf(fid, '** \n');
    fprintf(fid, '** Interaction: Int1\n');    
    fprintf(fid, '*Contact, op=NEW\n');
    fprintf(fid, '*Contact Inclusions, ALL EXTERIOR\n');
    fprintf(fid, '*Contact Property Assignment\n');
    fprintf(fid, ' ,  , IntProp-1\n');
    fprintf(fid, '** OUTPUT REQUESTS\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Restart, write, number interval=8, time marks=NO\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** FIELD OUTPUT: F-Output-1\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Output, field, time interval=0.01\n');
    fprintf(fid, '*Node Output\n');
    fprintf(fid, 'U, COORD\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** FIELD OUTPUT: F-Output-2\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Element Output, directions=YES\n');
    fprintf(fid, 'LE, S, TEMP\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** HISTORY OUTPUT: H-Output-1\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Output, history, variable=PRESELECT, time interval=0.01\n');
    fprintf(fid, '*End Step\n');
    fprintf(fid, '** ----------------------------------------------------------------\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** STEP: Step-2\n');
    fprintf(fid, '** \n');
    fprintf(fid, '*Step, name=Step-2, nlgeom=YES\n');
    fprintf(fid, '*Dynamic, Explicit\n');
    fprintf(fid, ', 0.17\n');
    fprintf(fid, '*Bulk Viscosity\n');
    fprintf(fid, '0.06, 1.2\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** Mass scaling\n');
    fprintf(fid, '*Fixed Mass Scaling, dt=0.000005, type=below min\n');
    fprintf(fid, '** \n');
    fprintf(fid, '** PREDEFINED FIELDS\n');
    fprintf(fid, '** \n');  
    fprintf(fid, '** Name: Predefined Field-4   Type: Temperature\n');
    fprintf(fid, '*Temperature, amplitude = Amp-tabular2\n'); 
    fprintf(fid, 'BRAIN-1.SET-NODE-GRAY, 1\n'); 
    fprintf(fid, '** Name: Predefined Field-5   Type: Temperature\n');
    fprintf(fid, '*TEMPERATURE, amplitude = Amp-tabular3\n');
    fprintf(fid, 'BRAIN-1.SET-NODE-WHITE, 0.091\n');   
    fprintf(fid, '*End Step\n');
    fclose(fid);
    
    disp(['ABAQUS .inp file written to ', filename]);
end